[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_BASE_PATH = "/"

# Handle SPA routing - this ensures that direct URLs like /login work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Handle asset paths
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/AimRV/assets/*"
  to = "/assets/:splat"
  status = 200

# Ensure assets are served correctly
[[headers]]
  for = "/assets/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.jsx"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
