name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup temporary directory
        run: |
          mkdir -p temp_deploy
          cp -r public/* temp_deploy/
          cp public/static.html temp_deploy/index.html
          touch temp_deploy/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./temp_deploy
          force_orphan: true
